### ISSUE TITLE
Mensualidades

### ISSUE THREAD

**Issue by ghost** [Falzar25/Contable_Arco#3]
* Cuando terminas de asignar un pago, se le puede apretar otra vez por error, hijole compa
* No has hecho los reportes vale
* Creeee un usuario 'Leopoldo' le agrego 12 de saldo y despues abone 150 por lo que ahora la deuda es de "-138" (menos ciento..). Como ai que? XD me debes . Ah y 'Volver' no vuelve XD

**Comment by Falzar25** [comment]
Corregido.
Reportes se completarán cuando mi computadora reviva.
